title = "Value sets"

[interested_5_scale]
values.de = [ "sehr interessiert", "eher interessiert", "eher nicht interessiert", "überhaupt nicht interessiert", "weiss nicht" ]
values.en = [ "very interested", "rather interested", "rather uninterested", "not interested at all", "don't know" ]
values.int = [ 1, 2, 3, 4, 99 ]
value_scale = "ordinal_descending"

[applicable_2_scale]
values.de = [ "trifft nicht zu", "trifft zu", "weiss nicht" ]
values.en = [ "is not true", "is true", "don't know" ]
values.int = [ 0, 1, 99 ]
value_scale = "binary"
