# ---- Questionnaire items ----

# ballot-related metadata
[ballot_date]
id = "ballot_date"
title.en = "ballot date"
title.de = "Abstimmungs-/Wahltermin"
description.en = "date of the ballot"
value_scale = "interval"
targets = [ "none" ]
[ballot_type]
id = "ballot_type"
title.en = "ballot type"
title.de = "Urnengang-Typ"
description.en = "type of the ballot"
values.en = [ "referendum", "election", "both" ]
values.de = [ "Abstimmung", "Wahl", "beides" ]
values.int = [ 1, 2, 3 ]
value_scale = "nominal"
targets = [ "none" ]

# official register data
[last_name_official]
id = "last_name_official"
title.en = "last name (official information)[^anon]"
title.de = "Nachname (amtliche Information)[^anon]"
description.en = "respondent's last name (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[first_name_official]
id = "first_name_official"
title.en = "first name (official information)[^anon]"
title.de = "Vorname (amtliche Information)[^anon]"
description.en = "respondent's first name (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[middle_name_official]
id = "middle_name_official"
title.en = "middle name(s) (official information)[^anon]"
title.de = "Weitere Vornamen (amtliche Information)[^anon]"
description.en = "respondent's middle name(s) (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[street_official]
id = "street_official"
title.en = "street name (official information)[^anon]"
title.de = "Strasse (amtliche Information)[^anon]"
description.en = "street name of respondent's place of residence (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[street_number_official]
id = "street_number_official"
title.en = "street number (official information)[^anon]"
title.de = "Hausnummer (amtliche Information)[^anon]"
description.en = "street number of respondent's place of residence (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[zip_code_official]
id = "zip_code_official"
title.en = "zip code (official information)[^anon]"
title.de = "Postleitzahl (amtliche Information)[^anon]"
description.en = "zip code of respondent's place of residence (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[place_official]
id = "place_official"
title.en = "place (official information)[^anon]"
title.de = "Ort (amtliche Information)[^anon]"
description.en = "respondent's place of residence (official cantonal register information)"
value_scale = "nominal"
targets = [ "none" ]
[household_type_official]
id = "household_type_official"
title.en = "household type (official information)[^anon]"
title.de = "Typ des Privathaushalts (amtliche Information)[^anon]"
description.en = "type of household the respondent lives in (official cantonal register information)"
values.en = [
  "single-person household",
  "family household",
  "couple household without children",
  "couple household with children",
  "single-parent household with children",
  "non-family household (with or without relatives)",
  "multi-family household"
]
values.de = [
  "Einpersonenhaushalte",
  "Familienhaushalte",
  "Paare ohne Kinder im Haushalt",
  "Paare mit Kind(ern) im Haushalt",
  "Einelternhaushalte mit Kind(ern)",
  "Nichtfamilienhaushalte (mit und ohne Verwandte)",
  "Mehrfamilienhaushalte"
]
values.int = [ 10, 20, 210, 220, 230, 30, 40 ]
value_scale = "nominal"
targets = [ "none" ]
[arrival_date_official]
id = "arrival_date_official"
title.en = "arrival date (official information)[^anon]"
title.de = "Zuzugsdatum (amtliche Information)[^anon]"
description.en = "respondent's date of arrival in the current `canton` (official cantonal register information)"
value_scale = "interval"
targets = [ "none" ]
[origin_canton_official]
id = "origin_canton_official"
title.en = "origin canton (official information)[^anon]"
title.de = "Herkunftskanton (amtliche Information)[^anon]"
description.en = "canton where the respondent lived before moving to the current `canton` (official cantonal register information)"
values.en = [
  "Zurich",
  "Berne",
  "Lucerne",
  "Uri",
  "Schwyz",
  "Obwalden",
  "Nidwalden",
  "Glarus",
  "Zug",
  "Fribourg",
  "Solothurn",
  "Basel-City",
  "Basel-Country",
  "Schaffhausen",
  "Appenzell Outer-Rhodes",
  "Appenzell Inner-Rhodes",
  "St. Gallen",
  "Grisons",
  "Aargau",
  "Thurgovia",
  "Ticino",
  "Vaud",
  "Valais",
  "Neuchâtel",
  "Geneva",
  "Jura"
]
values.de = [
  "Zürich",
  "Bern",
  "Luzern",
  "Uri",
  "Schwyz",
  "Obwalden",
  "Nidwalden",
  "Glarus",
  "Zug",
  "Freiburg",
  "Solothurn",
  "Basel-Stadt",
  "Basel-Landschaft",
  "Schaffhausen",
  "Appenzell Ausserrhoden",
  "Appenzell Innerrhoden",
  "St. Gallen",
  "Graubünden",
  "Aargau",
  "Thurgau",
  "Tessin",
  "Waadt",
  "Wallis",
  "Neuenburg",
  "Genf",
  "Jura"
]
values.int = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 ]
value_scale = "nominal"
targets = [ "none" ]
[year_of_birth_official]
id = "year_of_birth_official"
title.en = "year of birth (official information)[^anon]"
title.de = "Geburtsjahr (amtliche Information)[^anon]"
description.en = "respondent's year of birth (official cantonal register information)"
value_scale = "interval"
targets = [ "none" ]
[sex_official]
id = "sex_official"
title.en = "sex (official information)[^anon]"
title.de = "Geschlecht (amtliche Information)[^anon]"
description.en = "respondent's sex (official cantonal register information)"
values.en = [ "male", "female", "indeterminate" ]
values.de = [ "männlich", "weiblich", "unbestimmt" ]
values.int = [ 1, 2, 3 ]
value_scale = "nominal"
targets = [ "none" ]
[marital_status_official]
id = "marital_status_official"
title.en = "TODO"
title.de = "Zivilstand (amtliche Information)[^anon]"
description.en = "respondent's marital status (official cantonal register information)"
values.en = [ "single", "married", "widowed", "divorced", "in civil union", "dissolved civil union" ]
values.de = [ "ledig", "verheiratet", "verwitwet", "geschieden", "in eingetragener Partnerschaft", "aufgelöste Partnerschaft" ]
values.int = [ 1, 2, 3, 4, 6, 7 ]
value_scale = "nominal"
targets = [ "none" ]
[household_size_official]
id = "household_size_official"
title.en = "TODO"
title.de = "Haushaltsgrösse (amtliche Information)[^anon]"
description.en = "number of persons living in respondent's household (official cantonal register information)"
value_scale = "ratio"
targets = [ "none" ]
[n_kids_in_household_official]
id = "n_kids_in_household_official"
title.en = "TODO"
title.de = "Anzahl Kinder im Haushalt (amtliche Information)[^anon]"
description.en = "number of underaged persons living in respondent's household (official cantonal register information)"
value_scale = "ratio"
targets = [ "none" ]

# personal data
[year_of_birth]
id = "year_of_birth"
title.en = "TODO"
title.de = "Geburtsjahr (Kontrollfrage)"
description.en = "respondent's year of birth (own statement)"
question.de = "In welchem Jahr sind Sie geboren?"
value_scale = "interval"
targets = [ "all" ]
is_mandatory = true
[sex]
id = "sex"
title.en = "TODO"
title.de = "Geschlecht (Kontrollfrage)"
description.en = "respondent's sex (own statement)"
question.de = "Welches ist Ihr Geschlecht?"
values.en = [ "male", "female", "indeterminate/other" ]
values.de = [ "männlich", "weiblich", "unbestimmt/anderes" ]
values.int = [ 1, 2, 3 ]
value_scale = "nominal"
targets = [ "all" ]
is_mandatory = true
[cantonal_attachment]
id = "cantonal_attachment"
title.en = "TODO"
title.de = "Verbundenheit mit dem Kanton"
description.en = "how attached the respondent feels to his/her current `canton` of residence"
question.de = "Wie verbunden fühlen Sie sich mit dem Kanton { stringr::str_to_sentence(canton) } auf einer Skala von 0 (gar nicht verbunden) bis 4 (stark verbunden)?"
# description.en = "how attached the respondent feels to the canton of { stringr::str_to_sentence(canton) }"
values.en = [ "0 (not attached at all)", "1", "2", "3", "4 (strongly attached)", "don't know" ]
values.de = [ "0 (gar nicht verbunden)", "1", "2", "3", "4 (stark verbunden)", "weiss nicht" ]
values.int = [ 0, 1, 2, 3, 4, 99 ]
value_scale = "ordinal_ascending"
targets = [ "all" ]

# basic political data
[political_interest_cantonal]
id = "political_interest_cantonal"
title.en = "TODO"
title.de = "Politisches Interesse kantonal"
description.en = "respondent's interest in cantonal politics"
question.de = "Wie interessiert sind Sie im Allgemeinen an der Politik auf Kantonsebene? Ich bin …"
value_sets = [ "interest_4_scale", "dunno" ]
targets = [ "all" ]
[political_interest]
id = "political_interest"
title.en = "TODO"
title.de = "Politisches Interesse Schweiz"
description.en = "respondent's interest in Swiss politics"
question.de = "Wie interessiert sind Sie im Allgemeinen an der Schweizer Politik? Ich bin …"
value_sets = [ "interest_4_scale", "dunno" ]
targets = [ "all" ]
[has_voted]
id = "has_voted"
title.en = "TODO"
title.de = "Teilnahme"
description.en = "respondent's participation status at the current ballot (blank votes count as 'has participated')"
question.de = "Gerade erst fanden Wahlen oder Abstimmungen statt. Bei solchen nimmt normalerweise weniger als die Hälfte der Stimmberechtigten teil. Haben Sie an diesem Urnengang teilgenommen (leer einlegen zählt als Teilnahme)?"
# question.default.referendum = "Gerade erst fanden Abstimmungen statt. Bei solchen nimmt normalerweise weniger als die Hälfte der Stimmberechtigten teil. Haben Sie an der Abstimmung vom { stringi::stri_datetime_format(time = ballot_date, format = 'date_long', locale = lang_to_locale('de')) } teilgenommen oder nicht? (leer einlegen zählt als Teilnahme)"
# question.20180923_20181125.referendum = "Gerade erst fanden Abstimmungen statt. Bei solchen nimmt normalerweise weniger als die Hälfte der Stimmberechtigten teil. Haben Sie an der Abstimmung teilgenommen oder nicht? (leer einlegen zählt als Teilnahme)"
# question.default.election = "Gerade erst fanden Wahlen statt. Bei solchen nimmt normalerweise weniger als die Hälfte der Wahlberechtigten teil. Haben Sie an den Wahlen vom { stringi::stri_datetime_format(time = ballot_date, format = 'date_long', locale = lang_to_locale('de')) } teilgenommen (leer einlegen zählt als Teilnahme)?"
# question.20191020.election = "Gerade erst fanden Wahlen statt. Bei solchen nimmt normalerweise weniger als die Hälfte der Stimmberechtigten teil. Haben Sie an den Wahlen vom { stringi::stri_datetime_format(time = ballot_date, format = 'date_long', locale = lang_to_locale('de')) } teilgenommen (leer einlegen zählt als Teilnahme)?"
values.en = [ "not participated", "participated" ]
values.de = [ "nicht teilgenommen", "teilgenommen" ]
values.int = [ 0, 1 ]
value_scale = "ordinal_ascending"
targets = [ "all" ]
is_mandatory = true
